### ISSUE TITLE
Zammad 5.1 Released

### ISSUE THREAD

**Issue by compgeniuses** [mrmarkuz/nethserver-zammad5#1]
Hi, a new version of Zammad has been released, could you be kind to update to this release.
thank you.

**Comment by mrmarkuz** [comment]
I updated the package, please reinstall:

`yum reinstall https://mrmarkuz.dynu.net/mirror/devtest/nethserver-zammad5-1.0.0-1.ns7.noarch.rpm`

To upgrade Zammad to the most recent version you can now execute:

`signal-event nethserver-zammad5-upgrade`

**Comment by compgeniuses** [comment]
Fantastic
